site_name: HEXENFLAME
nav:
  - О сеттинге:
    - Что такое HEXENFLAME: start/index.md
    - Космогония: start/about_cosmogony.md
    - Вопрос веры: start/about_faith.md
    - Ведьмовской огонь: start/about_magic.md
    - Мир, доставшийся людям: start/about_story.md
    - Кто я: start/who_am_i.md
    - Глоссарий: start/glossary.md


  - Мир:
    - Языки: world/languages.md
    - Времяисчисление: world/time.md
    - Деньги: world/money.md
    - Аспекты: 
      - Скрытые знания: world/aspects/hidden_lore.md
      - Магические традиции: world/aspects/magic_traditions.md


  - Вера:
    - В начале времён: faith/the_beggining.md
    - Свет:
      - Триединство:
        - Триединство: faith/light/trinity/about_trinity.md
        - Ответвления веры: faith/light/trinity/faith_paths.md
      # - Дитя Света: 
      #   - Дитя Света: faith/light/child_of_light/about_child.md


    - Старые Боги: 
      - О старых богах: faith/old_gods/about_old_gods.md
      - Эфермон: faith/old_gods/efermon.md
      - Нан-Иза́ф: faith/old_gods/nan-izaf.md
      - Сетхе́б: faith/old_gods/setheb.md
      - Софода́н: faith/old_gods/sofodan.md
      - Айн-Дарра́х: faith/old_gods/ain-darrah.md
    
    - Нетленный: faith/father/about_father.md


  - Государства и нации:
    - Святая Холархия: 
      - О Святой Холархии: nations/holy_holarchy/about_hh.md
      - Холоны: nations/holy_holarchy/holons_of_hh.md
    
    - Княжества Железного Колеса: 
      - Оссильон: nations/iron_wheel/ossilion.md
      # - Дюнхольц: nations/iron_wheel/dunholtz.md
      # - Гарруаль: nations/iron_wheel/garrual.md
      # - Эшенфаль: nations/iron_wheel/eshenfal.md
      # - Люнн-Труа: nations/iron_wheel/lunn-trua.md
      # - Золльланд: nations/iron_wheel/zolland.md]
      # - Готтланд: nations/iron_wheel/gottland.md
    
    # - Вольные княжества:
    #   - Фалькенштайн: nations/free/falkenstein.md


  - Культы:
    - Культы Нетленного: 
      - Культ Мёртвой Луны:
        - О культе: cults/father/dmc/about_dmc.md
        - Догматы: cults/father/dmc/dogma_dmc.md
        - Вера: cults/father/dmc/faith_dmc.md
        - Прозелетизм: cults/father/dmc/proselytism_dmc.md
        - Структура: cults/father/dmc/power_dmc.md

theme: 
  name: 'material'
  palette:
    primary: custom
    accent: custom
    scheme: slate
  font:
    text: 'Roboto'
    code: 'Oswald Thin'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - search
  language: ru
  logo: images/deadmooncult_ico.ico
  favicon: images/deadmooncult_favico.png
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-timeline.css
extra:
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
  generator: false
plugins:
  - search
  - tags
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - smarty
  - tables
  - def_list
  - footnotes
  - md_in_html
  - meta
  - neoteroi.timeline