site_name: Hexenflame
nav:
  # - ВВЕДЕНИЕ:
  #   - Вдохновение: hexenflame/00_introduction/insp.md
  - ФРАГМЕНТЫ ИСТИНЫ:
    - Космогония: hexenflame/01_fragments-of-truth/Cosmogony.md
    - Вера и Боги: hexenflame/01_fragments-of-truth/Faith-and-Gods.md
    - Ведьмовской Огонь: hexenflame/01_fragments-of-truth/Hexenflame.md
    - Чёрные Псалмы: hexenflame/01_fragments-of-truth/Black-Psalms.md
    - Вирмы: hexenflame/01_fragments-of-truth/Wyrms.md
  - ЛЮДИ:
    - Кровь и Происхождение: hexenflame/02_the-peoples/Blood-and-Origins.md
    - Кто разделяет и властвует: hexenflame/02_the-peoples/Who-Divide-and-Rule.md
  - СКИТАЛЬЦЫ:
    - Резонансы: hexenflame/03_the-wanderers/Resonance.md
    - Скиталец: hexenflame/03_the-wanderers/Wanderer.md
    - Архетипы: hexenflame/03_the-wanderers/Archetypes.md
  - ВЕРА, КУЛЬТЫ И УБЕЖДЕНИЯ:
    - Метафизика:
      - Отблески: hexenflame/04_faith-cult-and-beliefs/Glimpses.md
    # - Свет:
    - Тьма:
      - Правда о Новых Богах: hexenflame/04_faith-cult-and-beliefs/Truth-about-New-Gods.md
      - Меньшие Сущности: hexenflame/04_faith-cult-and-beliefs/Lesser-Entities.md
    # - Всеотец:
  - СТАЛЬ И КРОВЬ:
    - Искусство Алхимии: hexenflame/05_steel-and-blood/Art-of-Alchemy.md
    - Арсенал Отчаяния: hexenflame/05_steel-and-blood/Arsenal-of-Despair.md
    - Фехтбух:
      - Боевые Навыки: hexenflame/05_steel-and-blood/MA_Martial-Skills.md
      - Заглавная: hexenflame/05_steel-and-blood/MA_Martial-Arts-Manual.md
      - Общие стили: hexenflame/05_steel-and-blood/MA_Common-Styles.md
      - Пути Святой Холархии: hexenflame/05_steel-and-blood/MA_Ways-of-Holy-Holarchy.md
      - Боевые Школы Айзенмарок: hexenflame/05_steel-and-blood/MA_Eisenmark-Combat-Schools.md
      - Искусства Павших Народов: hexenflame/05_steel-and-blood/MA_Arts-of-Fallen-Peoples.md

theme: 
  name: 'material'
  palette:
    - scheme: light
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Oswald Thin'
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - search
  language: ru
  logo: images/deadmooncult_ico.ico
  favicon: images/deadmooncult_favico.png
extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/neoteroi-timeline.css
extra:
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
  generator: false
plugins:
  - search
  - autolinks
  - tags:
      enabled: true
  - obsidian-bridge
  - obsidian-support
  - git-revision-date-localized
extra_javascript:
  - assets/javascripts/obsidian_tags.js
  - assets/javascripts/graph_force.js
markdown_extensions:
  - nl2br
  - abbr
  - admonition
  - attr_list
  - smarty
  - tables
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde